### ISSUE TITLE
Explore copier

### ISSUE THREAD

**Issue by astrojuanlu** [astrojuanlu/cookiecutter-pylib#15]
In my current job we're using cookiecutter a lot but I'm sad to see it's not maintained anymore, and I'm looking into Copier: https://github.com/copier-org/copier 

Apparently it solves some of the pain points of cookiecutter, for example the ability to _update_ a project with respect to a given template, and one minor thing: being able to start a project in the _current_ directory (rather than a subdirectory).

@OriolAbril have you ever heard of this?

**Comment by OriolAbril** [comment]
Hadn't heard of it but it sounds interesting!

**Comment by astrojuanlu** [comment]
Done :) there are some DX gaps but I like it! https://github.com/astrojuanlu/copier-pylib
