### ISSUE TITLE
Relases with release-notary?

### ISSUE THREAD

**Issue by martincollado** [astrojuanlu/cookiecutter-pylib#4]
https://github.com/aevea/release-notary

**Comment by astrojuanlu** [comment]
Interesting, thanks @mcolladoio ! I didn't know about https://www.conventionalcommits.org/en/v1.0.0/

Do you know how does this compare to https://github.com/hawkowl/towncrier ?

**Comment by astrojuanlu** [comment]
release-notary is not maintained anymore.
