### ISSUE TITLE
More opinionated choices on docs?

### ISSUE THREAD

**Issue by OriolAbril** [astrojuanlu/cookiecutter-pylib#6]
I used the template to create https://github.com/arviz-devs/xarray-einstats and it has made my job much much easier and more enjoyable, thank you so much. I have basically done only minor changes to the infrastructure build by the template in all areas _except on doc related things_. I know I am way more opinionated on those than I am on everything else, but there are still some things that I think could benefit everyone, not only doc focused people like me:

* Importing the project in `conf.py` for autosummary and autodoc to work
* Add some common things like `"Thumbs.db", ".DS_Store", ".ipynb_checkpoints"` to `exclude_patterns`
* Adding sphinx-copybutton to extensions. 
* Adding pydocstyle to `tox- e check`

Let me know what you think, I'd be happy to send a PR for some or all of these.

**Comment by astrojuanlu** [comment]
Glad that it served you well @OriolAbril ! I'm in favor of all the things you say except for mangling the path in `conf.py` for autodoc to find the code (shouldn't `pip install -e .` be enough? Or perhaps I misunderstood your proposal)

Feel free to send a PR and we can discuss it!

**Comment by OriolAbril** [comment]
> shouldn't pip install -e . be enough?

It is. This is probably more a reflection on my bad practices than nothing else :sweat_smile:. If I notice a typo or have a quick improvement idea while using the library (this or another one) I sometimes edit the docstrings and quickly check the rendering while still on the other environment that has no `pip -e` install. And this only works because sphinx+common extensions are basically in all my envs. 

I'll submit a PR for the other points in a few days :blush:
